[project]
authors = ["Seth Stadick <sstadick@gmail.com>", "Robert Cocker <https://robertcocker.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Useful things that aren't in the standard library."
name = "xmojo"
platforms = ["osx-arm64", "linux-64"]
version = "0.8.0"
license = "Unlicense OR MIT"

[tasks]
build = "magic run mojo package xmojo -o xmojo.mojopkg"
test = "magic run mojo test test_regex.mojo && mojo run test_file.mojo && mojo run test_bstr.mojo"
format = "magic run mojo format ./"

[dependencies]
max = ">=24.6.0,<25"
