context:
  version: "0.23.0"
  max_version: "=26.5.0"

package:
  name: "extramojo"
  version: ${{ version }}

source:
  # - git: https://github.com/ExtraMojo/ExtraMojo.git
  #   rev: 3282009a7cad20b77072b1cb930d96ea4bb73668
  path: .
  use_gitignore: true

build:
  number: 0
  script:
    - mojo precompile extramojo -o $PREFIX/lib/mojo/extramojo.mojoc
requirements:
  host:
    - max ${{ max_version }}
  run:
    - max ${{ max_version }}
    # - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo run -I $PREFIX/lib/mojo tests/test_file.mojo
          - mojo run -I $PREFIX/lib/mojo tests/test_bstr.mojo
          - mojo run -I $PREFIX/lib/mojo tests/test_bstr_parse.mojo
          - mojo run -I $PREFIX/lib/mojo tests/math/test_ops.mojo
          - mojo run -I $PREFIX/lib/mojo tests/collections/test_bitvec.mojo
          - mojo run -I $PREFIX/lib/mojo tests/collections/bbhash/test_hash.mojo
          - mojo run -I $PREFIX/lib/mojo tests/collections/bbhash/test_bbhash.mojo
    requirements:
      run:
        - max ${{ max_version }}
    files:
      recipe:
        - tests/test_file.mojo
        - tests/test_bstr.mojo
        - tests/test_bstr_parse.mojo
        - tests/math/test_ops.mojo
        - tests/collections/test_bitvec.mojo
        - tests/collections/bbhash/test_hash.mojo
        - tests/collections/bbhash/test_bbhash.mojo

about:
  homepage: https://github.com/ExtraMojo/ExtraMojo
  license: "(Unlicense OR MIT) AND MIT AND Apache-2.0 WITH LLVM-exception"
  license_file:
    - LICENSE-MIT
    - UNLICENSE
    - licenses/third-party/README.md
    - licenses/third-party/zig.txt
    - licenses/third-party/modular.txt
  summary: Extra functionality not yet in the standard library, mostly focused on strings and file IO.
  repository: https://github.com/ExtraMojo/ExtraMojo

extra:
  maintainers:
    - sstadick
  project_name: extramojo
